import type { Api } from "../api";
import type { Filters, Fish, Post, PostMarker, User, Waterbody } from "../types";
import type { SeenMap } from "../unread";

export type Store = {
  ready: boolean;
  api: Api;
  user: User | null;
  error: string;
  fish: Fish[];
  waterbodies: Waterbody[];
  waterbodyId: string;
  posts: Post[];
  markers: PostMarker[];
  nextCursor: string | null;
  selectedId: string | null;
  detail: Post | null;
  filters: Filters;
  rulerOn: boolean;
  seen: SeenMap;
  syncStamp: string;
  flyToId: string | null;
  boot: () => Promise<void>;
  login: (nickname: string, password: string, serverUrl: string) => Promise<void>;
  register: (nickname: string, password: string, serverUrl: string, invite?: string) => Promise<void>;
  logout: () => Promise<void>;
  setToken: (token: string, user: User) => Promise<void>;
  setWaterbody: (id: string, opts?: { keepPostId?: string }) => Promise<void>;
  setFilters: (patch: Partial<Filters>) => Promise<void>;
  selectPost: (id: string | null) => Promise<void>;
  refreshPosts: (opts?: { append?: boolean }) => Promise<void>;
  loadMorePosts: () => Promise<void>;
  refreshMarkers: () => Promise<void>;
  refreshDetail: (opts?: { skipList?: boolean }) => Promise<void>;
  openOnMap: (post: Post) => Promise<void>;
  toggleFavorite: (post: Post) => Promise<void>;
  markSeen: (post: Post) => void;
  toggleRuler: () => void;
  setError: (msg: string) => void;
  clearFlyTo: () => void;
};
