import type { Api } from "../api";
import type { FeedTouch } from "../features/spots/feedDelta";
import type { Filters, Fish, Post, PostMarker, User, Waterbody } from "../types";

export type Store = {
  ready: boolean;
  api: Api;
  user: User | null;
  error: string;
  fish: Fish[];
  waterbodies: Waterbody[];
  waterbodyId: string;
  posts: Post[];
  markers: PostMarker[];
  nextCursor: string | null;
  selectedId: string | null;
  detail: Post | null;
  filters: Filters;
  rulerOn: boolean;
  syncRev: number;
  flyToId: string | null;
  boot: () => Promise<void>;
  login: (nickname: string, password: string, serverUrl: string) => Promise<void>;
  register: (nickname: string, password: string, serverUrl: string, invite?: string) => Promise<void>;
  logout: () => Promise<void>;
  setToken: (token: string, user: User) => Promise<void>;
  setWaterbody: (id: string, opts?: { keepPostId?: string }) => Promise<void>;
  setFilters: (patch: Partial<Filters>) => Promise<void>;
  selectPost: (id: string | null, opts?: { reload?: boolean }) => Promise<void>;
  refreshPosts: (opts?: {
    append?: boolean;
    extra?: Post | null;
    sinceRev?: number;
    local?: Post;
  }) => Promise<FeedTouch | void>;
  loadMorePosts: () => Promise<void>;
  refreshDetail: (opts?: { skipList?: boolean }) => Promise<void>;
  openOnMap: (post: Post) => Promise<void>;
  toggleFavorite: (post: Post) => Promise<void>;
  toggleVote: (post: Post, value: "like" | "dislike") => Promise<void>;
  markSeen: (post: Post) => void;
  toggleRuler: () => void;
  setError: (msg: string) => void;
  clearFlyTo: () => void;
};
